---
# Copyright (C) 2023 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
    type: libvirt

platforms:
  - name: test-assets
    box: alvistack/ubuntu-22.04
    memory: 2048
    cpus: 2
    groups:
      - vpn
      - k8s_assets
      - k8s
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.5
  - name: test-controller1
    box: alvistack/ubuntu-22.04
    memory: 2048
    cpus: 2
    groups:
      - vpn
      - ubuntu22
      - k8s_controller
      - k8s_worker
      - k8s_etcd
      - k8s
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.10
  - name: test-controller2
    box: alvistack/ubuntu-22.04
    memory: 2048
    cpus: 2
    groups:
      - vpn
      - ubuntu22
      - k8s_controller
      - k8s_worker
      - k8s_etcd
      - k8s
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.20
  - name: test-controller3
    box: alvistack/ubuntu-20.04
    memory: 2048
    cpus: 2
    groups:
      - vpn
      - ubuntu20
      - k8s_controller
      - k8s_worker
      - k8s_etcd
      - k8s
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.30
  - name: test-worker1
    box: alvistack/ubuntu-22.04
    memory: 2048
    cpus: 2
    groups:
      - vpn
      - ubuntu22
      - k8s_worker
      - k8s
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.100
  - name: test-worker2
    box: alvistack/ubuntu-20.04
    memory: 2048
    cpus: 2
    groups:
      - vpn
      - ubuntu20
      - k8s_worker
      - k8s
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 172.16.10.110

provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
  log: true
  lint: yamllint . && flake8

scenario:
  name: default
  test_sequence:
    - prepare
    - converge

verifier:
  name: ansible
  enabled: true
